# Generated by Django 4.2.3 on 2023-09-01 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_manager', '0007_alter_workout_date_of_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='number_of_views',
            field=models.ManyToManyField(blank=True, related_name='workout_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
