# Generated by Django 4.2.3 on 2023-10-28 12:44

from django.db import migrations, models
import exercise_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_manager', '0010_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='preview',
            field=models.ImageField(blank=True, default='exercise_manager\\static\\img\\image.svg', upload_to=exercise_manager.utils.workout_preview_path),
        ),
    ]
