# Generated by Django 4.2.3 on 2023-10-29 12:20

from django.db import migrations, models
import exercise_manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_manager', '0014_workout_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='finalPositionImage',
            field=models.ImageField(blank=True, default='exercise_manager/static/img/image.svg', upload_to=exercise_manager.utils.exercise_img_path),
        ),
        migrations.AddField(
            model_name='exercise',
            name='startPositionImage',
            field=models.ImageField(blank=True, default='exercise_manager/static/img/image.svg', upload_to=exercise_manager.utils.exercise_img_path),
        ),
    ]
