# Generated by Django 4.0 on 2023-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_manager', '0015_exercise_finalpositionimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='exercise_manager.Exercise'),
        ),
    ]
