# Generated by Django 4.2.3 on 2023-07-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileplus',
            name='user_type',
            field=models.CharField(choices=[('T', 'Coach'), ('S', 'Sportsman')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
