# Generated by Django 4.2.3 on 2023-07-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofileplus_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileplus',
            name='user_type',
            field=models.CharField(choices=[('T', 'Coach'), ('S', 'Sportsman')], default='V', max_length=1),
        ),
    ]
