# Generated by Django 4.2.3 on 2023-07-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofileplus_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileplus',
            old_name='user_type',
            new_name='user_cat',
        ),
    ]
