# Generated by Django 4.2.3 on 2023-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_user_type_userprofileplus_user_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileplus',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileplus',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileplus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
