# Generated by Django 4.2.3 on 2023-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofileplus_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofileplus',
            options={'verbose_name': 'User Profile Plus', 'verbose_name_plural': 'User Profiles Plus'},
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exercises', models.ManyToManyField(to='authentication.exercise')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workout',
            },
        ),
    ]
