# Generated by Django 4.0 on 2023-11-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_workout_exercises_delete_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileplus',
            name='birth_date',
        ),
    ]
